export const TEMPLATE_LABELS = {
	'vite-react': 'Vite + React',
	'vite-vanilla': 'Vite + Vanilla JS',
	'vite-react-ts': 'Vite + React TS',
	'vite-vue': 'Vite + Vue',
	'vite-vanilla-ts': 'Vite + Vanilla TS',
	'plain-html': 'HTML + CSS + JS',
	node: 'Node + Express',
	fastify: 'Node + Fastify',
	koa: 'Node + Koa',
	python: 'Python HTTP Server',
	'python-cli': 'Python CLI App',
	php: 'PHP Built-in Server',
	java: 'Java HTTP Server',
	'java-console': 'Java Console App',
	'java-maven': 'Java + Maven App',
};

export const CLI_BACKEND_TEMPLATES = [
	'python-cli',
	'java-console',
	'java-maven',
];
export const MANAGED_APP_BACKEND_TEMPLATES = [
	'node',
	'fastify',
	'koa',
	'python',
	'php',
	'java',
];

/**
 * Converts a display value into a lower-case slug used by generated projects.
 *
 * @param {unknown} value - Raw text value to normalize.
 * @param {string} [fallback='workspace-app'] - Value to use when the input is empty.
 * @returns {string} Lower-case slug containing only letters, numbers, and dashes.
 */
export function slugifyToken(value, fallback = 'workspace-app') {
	const normalized = String(value || fallback)
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-+|-+$/g, '');

	return normalized || fallback;
}

/**
 * Returns the user-facing label for a project template id.
 *
 * @param {string | null | undefined} template - Template id stored on a project.
 * @returns {string} Human-readable template label.
 */
export function getTemplateLabel(template) {
	return TEMPLATE_LABELS[template] || template || 'None';
}

/**
 * Reports whether a backend template is terminal-driven instead of dashboard-managed.
 *
 * @param {string | null | undefined} template - Backend template id to inspect.
 * @returns {boolean} True when the backend runs from the editor terminal.
 */
export function isCliBackendTemplate(template) {
	return CLI_BACKEND_TEMPLATES.includes(template);
}

/**
 * Reports whether a backend template is a managed runtime process.
 *
 * @param {string | null | undefined} template - Backend template id to inspect.
 * @returns {boolean} True when the dashboard can start and stop the backend.
 */
export function isManagedAppBackendTemplate(template) {
	return MANAGED_APP_BACKEND_TEMPLATES.includes(template);
}

/**
 * Normalizes scaffold metadata from a project response for use in the UI.
 *
 * @param {object} [project={}] - Project record returned by the API.
 * @returns {{description: string, version: string, projectSlug: string, javaGroupId: string, javaPackageName: string, javaMainClass: string, javaQualifiedMainClass: string, javaArtifactId: string, javaVersion: string}} Normalized scaffold metadata.
 */
export function getProjectScaffold(project = {}) {
	const scaffold = project.scaffold || {};
	const name = project.name || 'workspace';
	const javaGroupId = scaffold.javaGroupId || 'com.dashboard';
	const javaPackageName = scaffold.javaPackageName || `${javaGroupId}.app`;
	const javaMainClass = scaffold.javaMainClass || 'App';
	const projectSlug = scaffold.projectSlug || slugifyToken(name);

	return {
		description:
			scaffold.description ||
			`${name} workspace generated by the dashboard.`,
		version: scaffold.version || '0.1.0',
		projectSlug,
		javaGroupId,
		javaPackageName,
		javaMainClass,
		javaQualifiedMainClass: `${javaPackageName}.${javaMainClass}`,
		javaArtifactId: scaffold.javaArtifactId || projectSlug,
		javaVersion: scaffold.javaVersion || '11',
	};
}

/**
 * Reports whether the project exposes operational monitoring metrics.
 *
 * @param {object} [project={}] - Project record returned by the API.
 * @returns {boolean} True when the project has managed services to monitor.
 */
export function hasOperationalMonitoring(project = {}) {
	return Boolean(
		project.hasManagedServices || project.runtime?.expectedServiceCount > 0,
	);
}

/**
 * Reports whether the project should show website-focused monitoring UI.
 *
 * @param {object} [project={}] - Project record returned by the API.
 * @returns {boolean} True when the project has a frontend and managed monitoring.
 */
export function hasWebsiteMonitoring(project = {}) {
	return Boolean(project.frontend) && hasOperationalMonitoring(project);
}

/**
 * Builds a short launch-mode label for a project card.
 *
 * @param {object} [project={}] - Project record returned by the API.
 * @returns {string} Human-readable launch category.
 */
export function getProjectLaunchLabel(project = {}) {
	const hasFrontend = Boolean(project.frontend);
	const hasManagedBackend = isManagedAppBackendTemplate(project.backend);
	const hasTerminalBackend = Boolean(project.backend && !hasManagedBackend);

	if (hasFrontend && hasManagedBackend) {
		return 'Web + service';
	}

	if (hasFrontend) {
		return 'Frontend app';
	}

	if (hasManagedBackend) {
		return 'Managed service';
	}

	if (hasTerminalBackend) {
		return 'Editor terminal';
	}

	return 'Custom workspace';
}

/**
 * Returns the primary file, class, or command a user should open first for a project.
 *
 * @param {object} [project={}] - Project record returned by the API.
 * @returns {string} Primary entry label shown in the UI.
 */
export function getProjectPrimaryEntry(project = {}) {
	const scaffold = getProjectScaffold(project);

	switch (project.backend) {
		case 'java':
		case 'java-console':
		case 'java-maven':
			return scaffold.javaQualifiedMainClass;
		case 'python':
			return 'app.py';
		case 'python-cli':
			return 'app.cli:main';
		case 'node':
		case 'fastify':
		case 'koa':
			return 'index.js';
		case 'php':
			return 'index.php';
		default:
			if (project.frontend === 'plain-html') {
				return 'index.html';
			}

			if (project.frontend) {
				return 'npm run dev';
			}

			return 'workspace';
	}
}

/**
 * Returns the first executable command for a project's command presets.
 *
 * @param {object} [project={}] - Project record returned by the API.
 * @returns {string | null} Primary command string, or null when no presets exist.
 */
export function getProjectPrimaryCommand(project = {}) {
	const preset =
		project.commandPresets?.find((entry) => entry.primary) ||
		project.commandPresets?.[0] ||
		null;

	return preset?.steps?.[0] || null;
}

/**
 * Returns a user-facing label for the main way to run or open a project.
 *
 * @param {object} [project={}] - Project record returned by the API.
 * @returns {string} Primary command label.
 */
export function getProjectCommandLabel(project = {}) {
	return (
		getProjectPrimaryCommand(project) ||
		project.commandPresets?.find((entry) => entry.primary)?.label ||
		project.commandPresets?.[0]?.label ||
		'Open editor'
	);
}

/**
 * Builds a concise runtime label for a project card.
 *
 * @param {object} [project={}] - Project record returned by the API.
 * @returns {string} Runtime summary label.
 */
export function getProjectRuntimeLabel(project = {}) {
	const scaffold = getProjectScaffold(project);

	switch (project.backend) {
		case 'java':
		case 'java-console':
		case 'java-maven':
			return `Java ${scaffold.javaVersion}`;
		case 'python':
		case 'python-cli':
			return 'Python workspace';
		case 'node':
		case 'fastify':
		case 'koa':
			return 'Node service';
		case 'php':
			return 'PHP workspace';
		default:
			if (project.frontend === 'plain-html') {
				return 'Static website';
			}

			if (project.frontend) {
				return 'Vite website';
			}

			return 'Custom workspace';
	}
}
