export const TEMPLATE_LABELS = {
	'vite-react': 'Vite + React',
	'vite-vanilla': 'Vite + Vanilla JS',
	'vite-react-ts': 'Vite + React TS',
	'vite-vue': 'Vite + Vue',
	'vite-vanilla-ts': 'Vite + Vanilla TS',
	'plain-html': 'HTML + CSS + JS',
	node: 'Node + Express',
	fastify: 'Node + Fastify',
	koa: 'Node + Koa',
	python: 'Python HTTP Server',
	'python-cli': 'Python CLI App',
	php: 'PHP Built-in Server',
	java: 'Java HTTP Server',
	'java-console': 'Java Console App',
	'java-maven': 'Java + Maven App',
};

export const CLI_BACKEND_TEMPLATES = ['python-cli', 'java-console', 'java-maven'];
export const MANAGED_APP_BACKEND_TEMPLATES = [
	'node',
	'fastify',
	'koa',
	'python',
	'php',
	'java',
];

export function slugifyToken(value, fallback = 'workspace-app') {
	const normalized = String(value || fallback)
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-+|-+$/g, '');

	return normalized || fallback;
}

export function getTemplateLabel(template) {
	return TEMPLATE_LABELS[template] || template || 'None';
}

export function isCliBackendTemplate(template) {
	return CLI_BACKEND_TEMPLATES.includes(template);
}

export function isManagedAppBackendTemplate(template) {
	return MANAGED_APP_BACKEND_TEMPLATES.includes(template);
}

export function getProjectScaffold(project = {}) {
	const scaffold = project.scaffold || {};
	const name = project.name || 'workspace';
	const javaGroupId = scaffold.javaGroupId || 'com.dashboard';
	const javaPackageName = scaffold.javaPackageName || `${javaGroupId}.app`;
	const javaMainClass = scaffold.javaMainClass || 'App';
	const projectSlug = scaffold.projectSlug || slugifyToken(name);

	return {
		description:
			scaffold.description ||
			`${name} workspace generated by the dashboard.`,
		version: scaffold.version || '0.1.0',
		projectSlug,
		javaGroupId,
		javaPackageName,
		javaMainClass,
		javaQualifiedMainClass: `${javaPackageName}.${javaMainClass}`,
		javaArtifactId: scaffold.javaArtifactId || projectSlug,
		javaVersion: scaffold.javaVersion || '11',
	};
}

export function hasOperationalMonitoring(project = {}) {
	return Boolean(
		project.hasManagedServices || project.runtime?.expectedServiceCount > 0,
	);
}

export function hasWebsiteMonitoring(project = {}) {
	return Boolean(project.frontend) && hasOperationalMonitoring(project);
}

export function getProjectLaunchLabel(project = {}) {
	const hasFrontend = Boolean(project.frontend);
	const hasManagedBackend = isManagedAppBackendTemplate(project.backend);
	const hasTerminalBackend = Boolean(project.backend && !hasManagedBackend);

	if (hasFrontend && hasManagedBackend) {
		return 'Web + service';
	}

	if (hasFrontend) {
		return 'Frontend app';
	}

	if (hasManagedBackend) {
		return 'Managed service';
	}

	if (hasTerminalBackend) {
		return 'Editor terminal';
	}

	return 'Custom workspace';
}

export function getProjectPrimaryEntry(project = {}) {
	const scaffold = getProjectScaffold(project);

	switch (project.backend) {
		case 'java':
		case 'java-console':
		case 'java-maven':
			return scaffold.javaQualifiedMainClass;
		case 'python':
			return 'app.py';
		case 'python-cli':
			return 'app.cli:main';
		case 'node':
		case 'fastify':
		case 'koa':
			return 'index.js';
		case 'php':
			return 'index.php';
		default:
			if (project.frontend === 'plain-html') {
				return 'index.html';
			}

			if (project.frontend) {
				return 'npm run dev';
			}

			return 'workspace';
	}
}

export function getProjectPrimaryCommand(project = {}) {
	const preset =
		project.commandPresets?.find((entry) => entry.primary) ||
		project.commandPresets?.[0] ||
		null;

	return preset?.steps?.[0] || null;
}

export function getProjectCommandLabel(project = {}) {
	return (
		getProjectPrimaryCommand(project) ||
		project.commandPresets?.find((entry) => entry.primary)?.label ||
		project.commandPresets?.[0]?.label ||
		'Open editor'
	);
}

export function getProjectRuntimeLabel(project = {}) {
	const scaffold = getProjectScaffold(project);

	switch (project.backend) {
		case 'java':
		case 'java-console':
		case 'java-maven':
			return `Java ${scaffold.javaVersion}`;
		case 'python':
		case 'python-cli':
			return 'Python workspace';
		case 'node':
		case 'fastify':
		case 'koa':
			return 'Node service';
		case 'php':
			return 'PHP workspace';
		default:
			if (project.frontend === 'plain-html') {
				return 'Static website';
			}

			if (project.frontend) {
				return 'Vite website';
			}

			return 'Custom workspace';
	}
}
