const path = require('path');

const DEFAULT_PROJECT_VERSION = '0.1.0';
const DEFAULT_PROJECT_DESCRIPTION_SUFFIX =
	'workspace generated by the dashboard.';
const DEFAULT_JAVA_GROUP_ID = 'com.dashboard';
const DEFAULT_JAVA_VERSION = '11';
const DEFAULT_JAVA_MAIN_CLASS = 'App';

function normalizeText(value, fallback = '') {
	if (typeof value !== 'string') {
		return fallback;
	}

	const trimmed = value.trim();
	return trimmed || fallback;
}

function slugifyToken(value, fallback = 'workspace-app') {
	const normalized = normalizeText(value, fallback)
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-+|-+$/g, '');

	return normalized || fallback;
}

function normalizeVersion(value, fallback = DEFAULT_PROJECT_VERSION) {
	const normalized = normalizeText(value, fallback);
	return /^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(normalized)
		? normalized
		: fallback;
}

function normalizeJavaGroupId(value, fallback = DEFAULT_JAVA_GROUP_ID) {
	const normalized = normalizeText(value, fallback)
		.toLowerCase()
		.replace(/[^a-z0-9.-]+/g, '.')
		.replace(/\.{2,}/g, '.')
		.replace(/^-+|-+$/g, '')
		.replace(/^\.+|\.+$/g, '');

	return normalized || fallback;
}

function normalizeJavaPackageName(value, fallback) {
	const packageFallback = fallback || `${DEFAULT_JAVA_GROUP_ID}.app`;
	const candidate = normalizeText(value, packageFallback);
	const segments = candidate
		.split('.')
		.map((segment) =>
			segment
				.toLowerCase()
				.replace(/[^a-z0-9_]/g, '')
				.replace(/^[^a-z_]+/, 'app'),
		)
		.filter(Boolean);

	return segments.length > 0 ? segments.join('.') : packageFallback;
}

function normalizeJavaClassName(value, fallback = DEFAULT_JAVA_MAIN_CLASS) {
	const candidate = normalizeText(value, fallback)
		.replace(/[^A-Za-z0-9_$]+/g, ' ')
		.split(' ')
		.filter(Boolean)
		.map((segment) => `${segment[0].toUpperCase()}${segment.slice(1)}`)
		.join('');

	const normalized = candidate || fallback;
	return /^[A-Za-z_$]/.test(normalized) ? normalized : fallback;
}

function normalizeJavaVersion(value, fallback = DEFAULT_JAVA_VERSION) {
	const normalized = normalizeText(value, fallback);
	return /^\d{1,2}$/.test(normalized) ? normalized : fallback;
}

function resolveProjectScaffold(input = {}, existingProject = {}) {
	const existingScaffold = existingProject?.scaffold || {};
	const scaffoldInput = input?.scaffold || {};
	const name = normalizeText(input.name, existingProject.name || 'workspace');
	const projectSlug = slugifyToken(
		scaffoldInput.projectSlug ?? input.projectSlug ?? existingScaffold.projectSlug ?? name,
	);
	const javaGroupId = normalizeJavaGroupId(
		scaffoldInput.javaGroupId ??
			input.javaGroupId ??
			existingScaffold.javaGroupId,
		DEFAULT_JAVA_GROUP_ID,
	);
	const defaultJavaPackageName = `${normalizeJavaPackageName(javaGroupId, DEFAULT_JAVA_GROUP_ID)}.app`;
	const javaPackageName = normalizeJavaPackageName(
		scaffoldInput.javaPackageName ??
			input.javaPackageName ??
			existingScaffold.javaPackageName,
		defaultJavaPackageName,
	);
	const javaMainClass = normalizeJavaClassName(
		scaffoldInput.javaMainClass ??
			input.javaMainClass ??
			existingScaffold.javaMainClass,
		DEFAULT_JAVA_MAIN_CLASS,
	);
	const javaArtifactId = slugifyToken(
		scaffoldInput.javaArtifactId ??
			input.javaArtifactId ??
			existingScaffold.javaArtifactId ??
			projectSlug,
	);
	const description = normalizeText(
		scaffoldInput.description ??
			input.description ??
			existingScaffold.description,
		`${name} ${DEFAULT_PROJECT_DESCRIPTION_SUFFIX}`,
	);
	const version = normalizeVersion(
		scaffoldInput.version ?? input.version ?? existingScaffold.version,
		DEFAULT_PROJECT_VERSION,
	);
	const javaVersion = normalizeJavaVersion(
		scaffoldInput.javaVersion ??
			input.javaVersion ??
			existingScaffold.javaVersion,
		DEFAULT_JAVA_VERSION,
	);
	const javaPackagePath = javaPackageName.split('.').join('/');
	const javaQualifiedMainClass = `${javaPackageName}.${javaMainClass}`;

	return {
		description,
		projectSlug,
		version,
		javaArtifactId,
		javaGroupId,
		javaMainClass,
		javaPackageName,
		javaPackagePath,
		javaQualifiedMainClass,
		javaVersion,
	};
}

function getProjectScaffold(project = {}) {
	return resolveProjectScaffold(project, project);
}

function getJavaSourceRelativePath(scaffold, options = {}) {
	const normalizedScaffold = resolveProjectScaffold({ scaffold });
	const sourceRoot = options.mavenLayout ? 'src/main/java' : 'src';
	return path.posix.join(
		sourceRoot,
		normalizedScaffold.javaPackagePath,
		`${normalizedScaffold.javaMainClass}.java`,
	);
}

function getJavaQualifiedMainClass(scaffold) {
	return resolveProjectScaffold({ scaffold }).javaQualifiedMainClass;
}

module.exports = {
	DEFAULT_JAVA_GROUP_ID,
	DEFAULT_JAVA_MAIN_CLASS,
	DEFAULT_JAVA_VERSION,
	DEFAULT_PROJECT_VERSION,
	getJavaQualifiedMainClass,
	getJavaSourceRelativePath,
	getProjectScaffold,
	resolveProjectScaffold,
	slugifyToken,
};
